### ISSUE TITLE
Rich Text through API

### ISSUE THREAD

**Issue by Jaykju** [zammad/zammad-api-client-php#19]
The Rich Text that is input into Zammad itself is rendered as html when accessed through the API. 
When I try to submit some "formatted" text to a ticket article on ticket creation it is not working. 

I understand that it would be risky to accept html as input for the article body but would it be possible to allow some sort of formatting like `<b>` or `<i>` tags or even a completely different format.

**Comment by martini** [comment]
Hi @Jaykju 

I'm closing because it's a question and no bug report. For a bug report all technical stuff like payload, responses and used zammad version is needed.

Please go to http://community.zammad.org for community support or to https://zammad.com for professional services.

PS: The API is allowing rich text and formatting like `<b>` and `<i>`. You need to set the content_type to `text/html`.

 -Martin
