### ISSUE TITLE
Search for user – empty return

### ISSUE THREAD

**Issue by ma2t** [zammad/zammad-api-client-php#27]
Hello here,

I have exactly the same issue than @MrGeneration and @heini23 (#25).

If I follow his example:

- The client is calling "/api/v1/users/search?expand=1&query=mustermann%40musterfirma.de
- Zammad API return: _[]_

But, if I add **"&sort_by=created_at"** to the URL called by the client, Zammad return the user.

Tested with self-hosted Zammad  3.2 and 3.3.

To temporary fix this issue, I added the following line into src/Resource/AbstractResource.php search function:
`$url_parameters['sort_by'] = 'created_at';`

Maybe adding a param to this function to sort may be a good idea?

Thank you for your great work on Zammad!

**Comment by jepf** [comment]
Hi @ma2t 

thanks for reporting your issue.

Could you please try to rebuild the Elasticsearch index? There was a change in one of the last versions which requires this.

`zammad run rake searchindex:rebuild`

If this does not solve the problem so that you can remove the parameter sort_by again, we will try to find another solution. But maybe sort_by with a default value generally would be a good idea.

**Comment by ma2t** [comment]
Hello @jepf,

Rebuilding Elasticsearch index solved the issue, thank you!
