### ISSUE TITLE
Call to undefined method GuzzleHttp\Exception\ConnectException::getResponse()

### ISSUE THREAD

**Issue by TechPrivacyLab** [zammad/zammad-api-client-php#42]
In https://github.com/zammad/zammad-api-client-php/blob/83f0129a5e032ad1545f01eff3fa9aeea4a1ed85/src/HTTPClient.php#L183 the `getResponse()` method is undefined.

To reproduce it I put in the `ZammadAPIClient\Client` constructor a wrong URL:

```php
use ZammadAPIClient\Client;
$client = new Client([
    'url' => 'https://wrong.zammad.url', // Wrong URL to my Zammad installation
    ...
]);
```

In this case `$e` is an instance of `GuzzleHttp\Exception\ConnectException` with no `getResponse()` method.

**Comment by mgruner** [comment]
@TechPrivacyLab could you please check the changes in #51. This is the best I could come up with now, to only wrap the response if one exists, and re-throw the error otherwise.

@jepf do you perhaps remember why the [try/catch](https://github.com/zammad/zammad-api-client-php/blob/cb2691b62672c1a27a041a24165d7ff47a162ca4/src/HTTPClient.php#L183) was done at all? Is it really required?

**Comment by jepf** [comment]
> @jepf do you perhaps remember why the [try/catch](https://github.com/zammad/zammad-api-client-php/blob/cb2691b62672c1a27a041a24165d7ff47a162ca4/src/HTTPClient.php#L183) was done at all? Is it really required?

@mgruner 

The try/catch is common practice for error handling at this point.

Possible solutions:
a) try to find the right exception class which contains the response object (maybe there changed something in Guzzle)
b) or just output the message (`$e->getMessage()`)of the exception and return some kind of empty Guzzle request object.

Be sure to not break the behavior by returning something unexpected to the caller.

**Comment by mgruner** [comment]
@jepf can you check my proposed changes in #51 please? It should not break anything, because it a) returns the error response if one is available and b) does not cause an unrelated `RuntimeException` as it does right now (that's what this bug is about), but instead throws a proper meaningful exception.
