### ISSUE TITLE
Make Guzzles HTTP connect_timeout configurable or set a decent default

### ISSUE THREAD

**Issue by chriswd** [zammad/zammad-api-client-php#47]
In a current project I'm often interacting with the Zammad API. Due to system maintenance or connection issues, my requests sometimes time out. If this happens often enough (especially in a maintenance window), this keeps more and more of my server threads busy, because your PHP API client / [Guzzle (curl) waits forever for a connection by default](https://docs.guzzlephp.org/en/latest/request-options.html#connect-timeout). This leads to resource leaks until PHP max_execution_time kicks in, but that may take quite some time in queued jobs.

Please add an option to [make Guzzles 'connect_timeout' configurable](https://docs.guzzlephp.org/en/stable/request-options.html):

```
use ZammadAPIClient\Client;
$client = new Client([
    'url' => 'https://myinstance.zammad.com',
    'http_token' => 'something',
    'timeout' => 15,
    'connect_timeout' => 5, // new option
]);
```

**Comment by mgruner** [comment]
Good point. Would you like to create a PR?

**Comment by jepf** [comment]
@chriswd 

Please keep in mind that no Guzzle specific options should be used in ZammadAPIClient\Client as Guzzle could be replaced in the future.  When adding this option, it should be added to HTTPClient (https://github.com/zammad/zammad-api-client-php/blob/2724628a509772f5ecbce445d6b7bca6d2d01aad/src/HTTPClient.php#L140). Also, for simplicity, the value for connect_timeout could/should simply be taken from the already given timeout option instead of introducing a second timeout related option.

**Comment by chriswd** [comment]
@mgruner Sure, where yould I put this PR instead?

@jepf I agree, this should be put in this generic class. To use the value from "timeout" is okay to me, but often you may want to set a lower value to "connect_timeout", because this is a cheaper operation.

**Comment by mgruner** [comment]
@chriswd I decided to go with the solution proposed by @jepf (connect_timeout uses the same value as timeout). Package version 2.0.4 is released.
