### ISSUE TITLE
Is it possible to create a GDPR deletion task with this client?

### ISSUE THREAD

**Issue by misterunknown** [zammad/zammad-api-client-php#53]
Deleting users via this client ist mostly impossible, because of existing references to tickets etc. So is there a way to trigger a GDPR deleteion task with this client?

**Comment by MrGeneration** [comment]
https://docs.zammad.org/en/latest/api/user.html#delete

----

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
